---
clone:
  depth: 1
kind: pipeline
name: pipe
steps:
  - name: build
    image: archlinux:base-devel
    commands:
      - curl -LO "https://repo.archlinuxcn.org/x86_64/glibc-linux4-2.33-4-x86_64.pkg.tar.zst" && bsdtar -C / -xvf "glibc-linux4-2.33-4-x86_64.pkg.tar.zst"
      - pacman -Sy && pacman -S git bc inetutils python2 zip dtc clang lld llvm --noconfirm
      - git clone https://github.com/arter97/arm32-gcc/ --depth=1 -j$(nproc --all)
      - git clone https://github.com/arter97/arm64-gcc/ --depth=1 -j$(nproc --all)
      - wget https://github.com/Kaz205/clang-releases/releases/download/clang-r445002/clang-r445002.tar.xz
      - tar -I xz -xf clang-r445002.tar.xz && mv clang-r445002 google-clang
      - git clone https://github.com/Kaz205/AnyKernel3 -b renoir --depth=1
      - ./drone.sh
      - curl -i -T AnyKernel3/*.zip https://oshi.at
